### ISSUE TITLE
Twitter Links Broken

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ChainReactApp2019#100]
Also some talks, like Marc Horowitz.

**Comment by kevinvangelder** [comment]
If the Twitter link isn't present we shouldn't display the Twitter icon.

**Comment by robinheinze** [comment]
This is an issue with the backend data, which I didn't realize had just twitter handles instead of full links.

**Comment by kevinvangelder** [comment]
Resolved by https://github.com/infinitered/ir_website/pull/577
