### ISSUE TITLE
Profile name update is delayed until next app launch

### ISSUE THREAD

**Issue by ryanlntn** [infinitered/ChainReactApp2019#102]
An initial profile name update appears to work but subsequent profile name updates aren't reflected until the app is closed and relaunched.

**Comment by robinheinze** [comment]
cc @dabit3

**Comment by dabit3** [comment]
@ryanlntn I was unable to reproduce. Have you tried navigating away from a comment and then back into one? This works. I have noticed that if you change your name while in a comment view and then leave and come back that it is not changed until you navigate away and come back.
