### ISSUE TITLE
Venue and Info screens have noticeable lag when first opened

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ChainReactApp2019#103]
iPhone X

When I first load the app and tap the Venue and Info tabs, it takes long enough to load that I tapped again on both of them. What's causing the lengthy load time?

**Comment by robinheinze** [comment]
I would assume it's the map box feature,and the sponsor logos.

**Comment by brentvatne** [comment]
probably good to render the minimal amount of content initially and then fill in the rest of the content on the next frame

```js
state = {
  renderFullContent: false,
};

componentDidMount() {
  requestAnimationFrame(() => {
    this.setState({ renderFullContent: true });
  });
}

render() {
  return (
    <View>
      <SomeContent />
      {this.state.renderFullContent ? <OtherContent /> : null}
    </View>
  );
}
```

**Comment by robinheinze** [comment]
Thanks @brentvatne! I'll try that out!
