### ISSUE TITLE
No protection against obscene profile names

### ISSUE THREAD

**Issue by ryanlntn** [infinitered/ChainReactApp2019#104]
Not sure if this is something we're worried about.

**Comment by robinheinze** [comment]
cc @dabit3 Not sure how hard this would be. There's https://github.com/web-mech/badwords, but not a ton of time left.

@jamonholmgren Do you think this will be an issue? we have the CoC and the report function now, but usernames are more broad than individual comments.

**Comment by dabit3** [comment]
@jamonholmgren @robinheinze @ryanlntn we could just disable the ability to change the username assigned on app load?

**Comment by jamonholmgren** [comment]
Hm, good question. I think you should still be able to change the username. If we ensure they know to follow the Code of Conduct, we can deal with any issues as they come up. If it gets too hard to handle, we can always disable the feature entirely.
