### ISSUE TITLE
Able to Comment on Workshop Discussion without Signing In

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ChainReactApp2019#105]
I am able to comment in the discussions but I haven't signed in

**Comment by kevinvangelder** [comment]
This might be invalid? I thought we were implementing GitHub signin, but I don't see it under the Profile tab, so I guess it's just anonymous?

**Comment by robinheinze** [comment]
Yeah, as far as I know it's just anonymous cc @dabit3

**Comment by dabit3** [comment]
Yeah there is no sign in process at all. Users are automatically assigned a random username when the app loads and they can change it if they would like in the profile section.
