### ISSUE TITLE
Discussions kill switch

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ChainReactApp2019#106]
I want a last-resort ability to remove the discussion tabs from every talk immediately. Perhaps we could check the schedule JSON and add a "discussionEnabled" key to that JSON? Then it should disable the discussion tab.

High GAFO on this. I don't anticipate needing it, but if we do, we'll really want this ability.

**Comment by robinheinze** [comment]
This is a good call. I think I can do this fairly easily. I can also try to add an app-level flag which would disable everything all at once including the profile tab.
