### ISSUE TITLE
Panel: TJ Fallon Missing Photo and Bio

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ChainReactApp2019#112]

**Comment by robinheinze** [comment]
TJ Bio: https://infinitered.slack.com/archives/C4UTWMA3T/p1561041479071800?thread_ts=1560959940.060000&cid=C4UTWMA3T

**Comment by robinheinze** [comment]
Fixed with https://github.com/infinitered/ir_website/pull/580
