### ISSUE TITLE
Increase target area for Discussion Details back button

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ChainReactApp2019#115]
It's a bit hard to tap on the Discussion Details back buttons on my iPhone Xs Max. Only the arrow icon appears to respond to taps. IMO, the entire back button text (in green) should be tappable.

**Comment by kevinvangelder** [comment]
The text isn't associated with the back button, it just appears to be visually.

**Comment by derekgreenberg** [comment]
The fix for increasing the target area for the back button should include the text. What is shown in the app UI visually should match expected functionality, which is a back button with text that should respond to a tap on the text of the back button.

**Comment by robinheinze** [comment]
Also related to #98
