### ISSUE TITLE
Nitpicky request for text change on 7/11 Registration and Breakfast

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ChainReactApp2019#116]
I recommend changing this sentence: "Then grab some breakfast quiche to ..." to this: "Then grab some breakfast to..."

I am requesting removal of the word "quiche", because even though a vegetarian version of it will be offered at breakfast, vegans cannot eat anything made with eggs. Also, I just think "grab some breakfast" is punchier.

**Comment by robinheinze** [comment]
Fixed in https://github.com/infinitered/ir_website/pull/577
