### ISSUE TITLE
Amazon Alex/AWS - make AWS much smaller - so they appear same size

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#119]
Design thing?

**Comment by robinheinze** [comment]
This is an issue because the aspect ratio of the two logos is different (Alexa is wide and short and AWS is closer to square). I'll just put in a custom width for AWS so it look smaller.

**Comment by shawnidanner** [comment]
that would be fantastic!


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ
