### ISSUE TITLE
Airship logo barely legible

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#120]
Can we have design make it bigger?

**Comment by robinheinze** [comment]
This is just an issue with the way they designed their logo. If we make it big enough to be legible, then it will be way bigger than the others. We can't really change the way their logo is designed.

**Comment by shawnidanner** [comment]
eek okay, thanks


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ
