### ISSUE TITLE
Wifi - Playstation needs to be same size as gold (per our contract)

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#121]
Design

**Comment by robinheinze** [comment]
Are you talking about the playstation logo up by the wifi info, or the one down in additional sponsors?

**Comment by shawnidanner** [comment]
In Additional. They've already complained about sizing of their logo so I
want it as big as gold everywhere possible, please.


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
Gotcha. So it should be larger than the other additional sponsors? Or should they all be that big?

**Comment by shawnidanner** [comment]
gah it's hard. if it looks silly with different sizes, then make them all
bigger.

It's based of money spent basically, so parties cost a lot, wifi costs a
lot, but dev lifts paid $1000 for theirs which is one of the lowest. We
need to change this for future I'd say



Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
Gotcha, okay, I'll make PlayStation bigger and use judgement on the others, with input from design.

**Comment by shawnidanner** [comment]
👍



Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ
