### ISSUE TITLE
Additional Sponsors - all green text should be the same size

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#123]

**Comment by robinheinze** [comment]
Probably would work best if we took the text out of the asset and put it in with `<Text />`

**Comment by mlaco** [comment]
@shawnidanner I will need to be provided these assets with the text removed please

**Comment by shawnidanner** [comment]
can you tag the designers?


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ
