### ISSUE TITLE
Do we mean to link out to Uber, Lyft and How to use the MAX? 

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#125]

**Comment by robinheinze** [comment]
I don't think we had intended to. I can make this a nice to have, if we have time, but I'd say it's low priority. Max would be easy since it's just web. Uber is more complicated because we have to open the app.

**Comment by shawnidanner** [comment]
👍



Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by ryanlntn** [comment]
Addressed with #180
