### ISSUE TITLE
Can we add the three hotels to the map?

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#126]

**Comment by mlaco** [comment]
Particular hotels or should I just pick?

**Comment by shawnidanner** [comment]
the three that we recommended people to book - they're on our website

radisson red
marriott city center
benson (also the workshop location)



Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by mlaco** [comment]
@shawnidanner do you want these to be added under one of the existing categories?
![Screen Shot 2019-06-24 at 7 03 26 PM](https://user-images.githubusercontent.com/4466642/60057517-d564aa00-96b2-11e9-9c3e-e7f936f48bfd.png)

**Comment by robinheinze** [comment]
I would think new tab would be best, if that's possible

**Comment by shawnidanner** [comment]
Yea new tab with hotels
