### ISSUE TITLE
When I click Schedule from somewhere after I've been in it, it goes to the last place in schedule (ie About Vlad's talk) rather than Schedule Page

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#127]

**Comment by robinheinze** [comment]
I believe this was done intentionally.

**Comment by shawnidanner** [comment]
can we change it anyways and see what it looks like?


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
It's not a super trivial change. How high priority would you say this is?

**Comment by shawnidanner** [comment]
Making it bigger is MOST important, Centering horizontally depends how it
looks bigger I guess.


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
Wait, I assume you're talking about #131? This is the issue about going back to the schedule tab :)
