### ISSUE TITLE
Add Welcome Party to Wednesday at 5pm

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#128]
Hosted by Bumped 
US Bancorp Building 3rd floor
Show up thirsty and ready to meet new friends before the conf begins Thursday morning!

**Comment by robinheinze** [comment]
@sammilner17 I didn't realize there was another after party. Can I please get a small graphic for the schedule list, and a bigger one for the detail page? Similar to what we did with coffee breaks, except we should have the Bumped logo on both.

**Comment by robinheinze** [comment]
@mlaco The assets for this are in this slack thread https://infinitered.slack.com/archives/C4UTWMA3T/p1560963477063400.

**Comment by mlaco** [comment]
@shawnidanner does the afterparty end at 9pm?

**Comment by shawnidanner** [comment]
I do not have an end time from them
