### ISSUE TITLE
Welcome to Day 2 - can you put both MCs

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#130]

**Comment by robinheinze** [comment]
We can't do two images on the schedule list view. We can either do no image, or get a generic one from the designers. I can make it so both show up on the detail view.

**Comment by shawnidanner** [comment]
Maybe let's do both in detail view


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
Bug: If there are multiple speakers, we should list all of them, even if talk type isn't "panel"
