### ISSUE TITLE
On info Page - Thanks to Wifi - can we center and enlarge Playstation logo?

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#131]

**Comment by robinheinze** [comment]
Center in which direction?

**Comment by shawnidanner** [comment]
Right now it's way to the right. I mean in the center of the...center :-/


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ

**Comment by robinheinze** [comment]
It's lined up vertically with the label for wifi network right now so centering it would put it on top of that. This is exactly how it was in last years app. I can try to make it bigger though.

**Comment by shawnidanner** [comment]
ahhh so horizontally


Cheers,

Shawni Danner
Project Coordinator
Chain React <https://infinite.red/ChainReactConf> Organizer
Infinite Red, Inc.

ᐧ
