### ISSUE TITLE
Map info boxes show outside of map bounds

### ISSUE THREAD

**Issue by silasjmatson** [infinitered/ChainReactApp2019#134]
This prevents closing the info box in situations where the close button is outside of the map bounds
![Screenshot_20190619-132710](https://user-images.githubusercontent.com/1761481/59798194-65ab8500-9296-11e9-8185-e46869a4dd67.png)

**Comment by robinheinze** [comment]
@silasjmatson I think I'm a bit confused what the bug is. Are you saying that close `x` in the screenshot isn't tappable because it's outside the map bounds?

**Comment by kevinvangelder** [comment]
Oh, the mapbox probably needs to be overflow: hidden so that the top of the dialog is cut off instead of visible but not tappable. #114 is a related issue to auto-center when focusing an item on the map.

**Comment by robinheinze** [comment]
Does that mean they just have to scroll the map down in order to close the dialog?

**Comment by silasjmatson** [comment]
This is still an issue on Android. I am running the Android 10 beta, which is something to keep in mind.

Here's a screen recording of the issues: https://drive.google.com/file/d/1dGerfDlMH_JVgdk7ShJwzj8XFycMO_9V/view?usp=drivesdk
