### ISSUE TITLE
Day 1 Welcome Schedule Adjustment

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2019#138]
Currently, We have Jamon doing 15 minutes of welcome on the schedule.

Technically, Jamon (and @twerth?) Will open for 5 minutes, start the video and then the MCs will take it from there.

This isn't a big issue, but just just wondering if:
1. Todd's face should be there
2. There should be a spot with the MC photos there

**Comment by robinheinze** [comment]
The issue is only having space for one photo on the list view. I can make sure both Jamon and Todd as well as the MC's are displayed on the detail view though.
