### ISSUE TITLE
Times are localized

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2019#139]
While I like that the times are localized, I think they shouldn't be in this regard.
![image](https://user-images.githubusercontent.com/997157/59803166-49b4dd00-92b0-11e9-81dc-0454e9ee9b6a.png)

If people download the app before the day, it should still say 9AM start, so they can plan accordingly.  I think the locked in times would be more consistent for the user experience.

**Comment by robinheinze** [comment]
We should try and add https://github.com/marnusw/date-fns-tz to format the UTC date strings to PDT
