### ISSUE TITLE
Sometimes returning to app - Dead screen

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2019#146]
Today I opened the app and there's just a purple background.   No content.

I have to remove the app from memory and reload to get content.

**Comment by kevinvangelder** [comment]
I was able to get this yellowbox warning by going to the talk detail screen, doing the iOS multitask gesture, and returning to the app. May or may not be related to the issue in prod. 
![image](https://user-images.githubusercontent.com/1771152/60045230-29529d00-9679-11e9-985f-e1694a209963.png)

**Comment by robinheinze** [comment]
We're adding a listener for AppState but never removing it, that's probably causing the yellowbox. I haven't been able to repro Gant's issue solidly though, so no idea if that's it.
