### ISSUE TITLE
Duplicate usernames?

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ChainReactApp2019#149]
@dabit3 Is there anything that prevents duplicate usernames?

@jamonholmgren @GantMan Is this something we should be worried about?

**Comment by GantMan** [comment]
I don't think so.  I think we're reaching the end of the use for this conf.  As long as we can ban a device, I'm good.  I think @dabit3 is looking at making sure a unique device ID is associated.   No worries on duplicates of names.
