### ISSUE TITLE
Footer on info tab

### ISSUE THREAD

**Issue by benInfiniteRed** [infinitered/ChainReactApp2019#153]
The footer on the info tab has all info pushed to the far left and the logo is cut off. It looks like there would be enough space to horizontally align the link circles.

![footer](https://user-images.githubusercontent.com/50120763/59951854-c88c5000-943f-11e9-8274-999f6f69b538.jpeg)

**Comment by robinheinze** [comment]
Yep, definitely a bug, probably related to mis-calculating screen width. Thanks!

**Comment by robinheinze** [comment]
In the most recent build, this doesn't appear to be happening anymore. I'm going to close for now, but I'll reopen if it crops up again.
