### ISSUE TITLE
Fix TS compile errors

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ChainReactApp2019#169]
`yarn compile` is in bad shape. 

We'll need to fix the errors coming from our project, as well as the RN @types package.

**Comment by ryanlntn** [comment]
@robinheinze You may want to work of the upgrade-rn branch since I upgraded all the `@types` deps there.

**Comment by robinheinze** [comment]
Realized `tsconfig` was still pointing to `src` instead of `app`, so there are still errors. Re-opening.
