### ISSUE TITLE
Clean up RN dependencies

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ChainReactApp2019#172]
I think we are on incorrect versions of some of the core RN dependencies like:

- React
- Babel
- Jest

We should go through https://react-native-community.github.io/upgrade-helper/?from=0.57.8&to=0.59.5 to make sure we're on the right versions

**Comment by ryanlntn** [comment]
@robinheinze We should probably upgrade to 0.59.9 while we're at it.

**Comment by robinheinze** [comment]
I'm guessing #173 also goes well with this

**Comment by ryanlntn** [comment]
@robinheinze I actually have a branch with 0.59.9 mostly sorted out.

**Comment by robinheinze** [comment]
Awesome!
