### ISSUE TITLE
Back Button inside Vlad's discussion take multiple taps to go back 

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#185]

**Comment by shawnidanner** [comment]
actually randomly takes multiple presses

**Comment by ryanlntn** [comment]
@shawnidanner What device are you testing on? I'm not able to recreate this on my iPhone X.

**Comment by shawnidanner** [comment]
Android. Samsung Galaxy S10

**Comment by ryanlntn** [comment]
Hmmm. The most likely explanation is that we don't have any hitSlop on the button right now which would make smaller text only buttons hard to hit. I'll try adding some.
