### ISSUE TITLE
View Code of Conduct Button on Info page is cut off

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#187]

**Comment by shawnidanner** [comment]
all buttons, the text is too large for button or vice versa

**Comment by robinheinze** [comment]
@shawnidanner I think this is actually fixed in the latest build, once that shows up in the store. Sorry about that delay.

**Comment by ryanlntn** [comment]
@robinheinze It looks like this can still be an issue if someone is using large text via accessibility settings: 

<img width="379" alt="Screen Shot 2019-07-02 at 11 06 40 AM" src="https://user-images.githubusercontent.com/1944151/60535699-95588500-9cb9-11e9-9e1d-b92330bf5b80.png">

**Comment by robinheinze** [comment]
Ah, good point

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robinheinze** [comment]
We should change it to have fixed padding but variable container height 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
