### ISSUE TITLE
Reporting Chat UX issues

### ISSUE THREAD

**Issue by silasjmatson** [infinitered/ChainReactApp2019#199]
Two issues:

* The report is small and hard to tap, and there is no animation or feedback when successful. If two messages are similar, it could be very easy to report multiple messages due to the small button and the lack of an visual feedback. (This should probably be a swipe action)
* Reported messages show up again after leaving and re-entering the app.

Screencast of issues: https://drive.google.com/file/d/1-814YbP-gDVMHtOnQ3XGdhoKVEWfyF-_/view?usp=drivesdk

**Comment by robinheinze** [comment]
I can try to increase the toucable area and add a confirmation dialog.
