### ISSUE TITLE
Clicking on Jamon crashes app - 

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2019#69]
download latest - switch to Thursday - click jamon drill down app crashes.   App stays crashed, can't open it now.

Try to open app, I get black screen -> purple screen -> close.

Happens every time.

**Comment by robinheinze** [comment]
@GantMan I know this isn't a good solution, but does it help if you delete the app completely and re-download from testflight? Just gathering info.

**Comment by GantMan** [comment]
Did it.  Crashed again.

**Comment by robinheinze** [comment]
I just redeployed from my machine and it's not crashing anymore, so I'm guessing it's something about the way the CircleCI env is configured. Can you try again with build 25?

**Comment by robinheinze** [comment]
Just tested with build 26, which was from CI after I pushed a fix. No crash for me from my TestFlight build so I'm closing this. Thanks @GantMan!
