### ISSUE TITLE
Workshops confusion

### ISSUE THREAD

**Issue by GantMan** [infinitered/ChainReactApp2019#70]
Looks like - from this layout - Testing is set as beginner.  But Testing is intermediate.

Advanced is Vlad

And React Native Fundamentals is definitely not in advanced.   

![image](https://user-images.githubusercontent.com/997157/58910934-619b3700-86dc-11e9-94b3-fbf45769f6c0.png)

**Comment by robinheinze** [comment]
👍 This will be fixed when I finish https://trello.com/c/pmxT7yon/68-add-intermediate-track-schedulecell
