### ISSUE TITLE
Crash when coming back to the app after locking the phone - iOS

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ChainReactApp2019#78]
1. Be in the app
2. Lock your device
3. Unlock your device
4. App crashses

~I've only noticed this on my iPhoneX using the TestFlight build. I haven't been able to reproduce in DEV mode~

Repro'd in DEV mode on a physical device. Here is the error:

![Image from iOS](https://user-images.githubusercontent.com/6894653/59235139-c3f4ab80-8ba4-11e9-93b1-fbe53fefc430.png)

**Comment by robinheinze** [comment]
@dabit3 Maybe you can help with this one? Looks to be AWS AppSync related.

**Comment by dabit3** [comment]
Hey @robinheinze  I'm investigating now

**Comment by dabit3** [comment]
@robinheinze waiting to hear back from the team on this, but my first intuition would be to have a listener and when the app goes into the background, unsubscribe from the subscription and then resubscribe when they open the app back up.

**Comment by robinheinze** [comment]
@dabit3 Any update on this?
