### ISSUE TITLE
Splash Screen Logo Squished (Android)

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ChainReactApp2019#96]
![Screenshot_2019-06-17-15-48-42](https://user-images.githubusercontent.com/1771152/59641890-dd9f7100-9117-11e9-8f9f-2a4e149fd01c.png)

**Comment by robinheinze** [comment]
@kevinvangelder What device was this?

**Comment by robinheinze** [comment]
I've tried on a Pixel 2, and a Samsung Galaxy S5, and Pixel XL with no repro. 

I did get a repro on a Pixel 2 XL, which is the only emulator i have with resolution 1440x2880
