### ISSUE TITLE
Back button on talk details is incorrect (shows time)

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ChainReactApp2019#98]
In the talk details screen, the back button shows the time, but should really say "Schedule" or something.

![IMG_8F398F67798A-1](https://user-images.githubusercontent.com/1479215/59641869-ce202800-9117-11e9-861a-b04f034a6598.jpeg)

**Comment by kevinvangelder** [comment]
That's the screen title, so we probably need to have the designers take another look at it.

**Comment by robinheinze** [comment]
Yeah, as far as I can tell, this is an intentional part of the design. It would be easy enough to make it say "Schedule", but then you lose any indication on this page of what time the talk is that you're viewing
